#!/usr/bin/env python3
"""
Data preparation in the YOLO format (Phase B1).

Converts the Edge Impulse export (read through the SINGLE annotation gate,
labels.py from Phase A) to the layout the Ultralytics YOLO expects:

    yolo/dataset/
      images/train/*.jpg   labels/train/*.txt
      images/val/*.jpg     labels/val/*.txt
    yolo/data.yaml

** The YOLO label format (concept to learn) **
For each image `photo.jpg` there is a `photo.txt` with ONE LINE per object:

    <class> <cx> <cy> <w> <h>       # normalized 0..1; cx,cy = box CENTER

Crucial difference vs. Edge Impulse:
  - EI gives x,y = TOP-LEFT corner in absolute PIXELS.
  - YOLO wants the CENTER, normalized by the image width/height.
The conversion (cx=(x+w/2)/W, cy=(y+h/2)/H, w/W, h/H) is EXACTLY the same as
preprocess.box_to_target() from Phase A — logic already validated there.

Background image (no paddle) -> EMPTY .txt file. YOLO accepts it and uses it as
a negative (teaches "there is no paddle here"), just like we did in Phase A.

** Why only 1 class **
We unify "paddles"/"paddle" into a single class `paddle` (index 0). What matters
is WHERE the paddle is, not which one it is.

** split **
We keep the original Edge Impulse split: training/ -> train, testing/ -> val.
They are distinct sets from the export itself (no leakage).

Usage:
    yolo/.venv/bin/python yolo/prep_yolo.py
    yolo/.venv/bin/python yolo/prep_yolo.py --check   # + draws boxes to verify
"""

import argparse
import os
import shutil
import sys

# labels.py lives in training/ (Phase A) — it is the single annotation gate.
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT = os.path.dirname(_THIS_DIR)
sys.path.insert(0, os.path.join(_PROJECT, "training"))
from labels import load_split  # noqa: E402

import cv2  # noqa: E402

DATASET_DIR = os.path.join(_THIS_DIR, "dataset")
DATA_YAML = os.path.join(_THIS_DIR, "data.yaml")
CLASS_ID = 0  # paddle

# training/ from the export -> "train" in YOLO ; testing/ -> "val"
SPLIT_MAP = {"training": "train", "testing": "val"}


def box_to_yolo(box, img_w, img_h):
    """Box in pixels (top-left corner) -> (cx, cy, w, h) normalized 0..1 (center)."""
    cx = (box.x + box.w / 2.0) / img_w
    cy = (box.y + box.h / 2.0) / img_h
    w = box.w / img_w
    h = box.h / img_h
    # defensive clamp (some boxes touch the border), same as the Phase A preprocess
    return tuple(min(max(v, 0.0), 1.0) for v in (cx, cy, w, h))


def build_split(ei_split, yolo_split, use_symlink=True):
    img_dir = os.path.join(DATASET_DIR, "images", yolo_split)
    lbl_dir = os.path.join(DATASET_DIR, "labels", yolo_split)
    os.makedirs(img_dir, exist_ok=True)
    os.makedirs(lbl_dir, exist_ok=True)

    samples = load_split(ei_split)
    n_pos = n_bg = 0

    for s in samples:
        base = os.path.basename(s.path)
        stem = os.path.splitext(base)[0]

        # image: symlink (fast, does not duplicate ~200MB) or copy
        dst_img = os.path.join(img_dir, base)
        if os.path.lexists(dst_img):
            os.remove(dst_img)
        if use_symlink:
            os.symlink(os.path.abspath(s.path), dst_img)
        else:
            shutil.copy2(s.path, dst_img)

        # label: needs the REAL image dimensions to normalize
        img = cv2.imread(s.path)
        h0, w0 = img.shape[:2]
        lines = []
        for box in s.boxes:                      # ALL boxes (YOLO is multi-object)
            cx, cy, w, h = box_to_yolo(box, w0, h0)
            lines.append(f"{CLASS_ID} {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}")

        with open(os.path.join(lbl_dir, stem + ".txt"), "w") as f:
            f.write("\n".join(lines))          # empty = background (negative)

        if s.has_paddle:
            n_pos += 1
        else:
            n_bg += 1

    print(f"[{ei_split} -> {yolo_split}] {len(samples)} images  "
          f"(with paddle: {n_pos}, background: {n_bg})")
    return len(samples), n_pos, n_bg


def write_yaml():
    content = (
        f"# generated by prep_yolo.py — Phase B\n"
        f"path: {DATASET_DIR}\n"
        f"train: images/train\n"
        f"val: images/val\n"
        f"nc: 1\n"
        f"names: [paddle]\n"
    )
    with open(DATA_YAML, "w") as f:
        f.write(content)
    print(f"data.yaml -> {DATA_YAML}")


def check_grid(n=12):
    """Draws the YOLO boxes back onto the images (visual check)."""
    import numpy as np
    img_dir = os.path.join(DATASET_DIR, "images", "val")
    lbl_dir = os.path.join(DATASET_DIR, "labels", "val")
    tiles, count = [], 0
    for fn in sorted(os.listdir(img_dir)):
        if count >= n:
            break
        stem = os.path.splitext(fn)[0]
        lbl = os.path.join(lbl_dir, stem + ".txt")
        with open(lbl) as f:
            rows = [r.split() for r in f.read().splitlines() if r.strip()]
        if not rows:
            continue  # we only show positives in the grid
        img = cv2.imread(os.path.join(img_dir, fn))
        h0, w0 = img.shape[:2]
        for r in rows:
            _, cx, cy, w, h = map(float, r)
            x0 = int((cx - w / 2) * w0); y0 = int((cy - h / 2) * h0)
            x1 = int((cx + w / 2) * w0); y1 = int((cy + h / 2) * h0)
            cv2.rectangle(img, (x0, y0), (x1, y1), (0, 255, 0), 2)
        tiles.append(cv2.resize(img, (320, 320)))
        count += 1
    if not tiles:
        print("no positive found for the grid")
        return
    cols = 4
    while len(tiles) % cols:
        tiles.append(np.zeros((320, 320, 3), dtype="uint8"))
    rows_img = [np.hstack(tiles[i:i + cols]) for i in range(0, len(tiles), cols)]
    grid = np.vstack(rows_img)
    out = os.path.join(_THIS_DIR, "check_grid.png")
    cv2.imwrite(out, grid)
    print(f"check grid -> {out}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--copy", action="store_true",
                    help="copies the images instead of symlinking (uses more disk)")
    ap.add_argument("--check", action="store_true",
                    help="also generates check_grid.png with the boxes drawn")
    args = ap.parse_args()

    for ei_split, yolo_split in SPLIT_MAP.items():
        build_split(ei_split, yolo_split, use_symlink=not args.copy)
    write_yaml()
    if args.check:
        check_grid()


if __name__ == "__main__":
    main()
